# Site settings
title: HakimJ / Dev
description: HakimJ.Dev
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: HakimJ
user_description: Currently enrolled Bachelor`s Degree in Computer Science at National University of Malaysia. I love gadget and coding! but i am not considering myself a pro because there`s a long way journey to go. Feel free to email me if you have anything to share with me! Thanks! 
user_title: Web / Software Developer & Gadget Enthusiast
email: jurason96@gmail.com
twitter_username: AbdulHakimJ
github_username:  AbdulHakimJumari

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
